name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
      
    - name: Build APK (Skip tests for now)
      run: flutter build apk --release --no-tree-shake-icons
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: edubox-app
        path: build/app/outputs/flutter-apk/app-release.apk